// Auto-extracted seed data from RubberJointsAI C# application
// Source: /tmp/scan-RubberJointsAI/Data/RubberJointsAIRepository.cs

export const exercises = [
  // ── WARM-UP: Home ──
  {
    id: "brisk-walking",
    name: "Brisk Walking",
    category: "warmup_tool",
    targets: "Full Body",
    description: "Walk at a brisk pace to increase systemic blood flow",
    cues: "5-10 min | Moderate pace | Swing arms naturally",
    explanation: "Low-impact way to raise core temperature and lubricate joints",
    warning: "",
    phases: "1,2",
    defaultRx: "5 min",
  },
  {
    id: "arm-circles",
    name: "Arm Circles",
    category: "warmup_tool",
    targets: "Shoulders",
    description: "Circle arms forward and backward to lubricate shoulder joints",
    cues: "10 forward | 10 backward | Gradually increase size",
    explanation: "Lubricates the shoulder glenohumeral joints and warms rotator cuff",
    warning: "",
    phases: "1,2",
    defaultRx: "2 min",
  },
  {
    id: "leg-swings",
    name: "Leg Swings",
    category: "warmup_tool",
    targets: "Hips",
    description: "Swing legs front-to-back and side-to-side for hip prep",
    cues: "10 each direction per leg | Hold wall for balance",
    explanation: "Opens the hip joint and prepares the labrum for movement",
    warning: "Keep core engaged for stability",
    phases: "1,2",
    defaultRx: "2 min",
  },
  {
    id: "glute-bridges",
    name: "Glute Bridges",
    category: "warmup_tool",
    targets: "Glutes,Lower Back",
    description: "Lift hips from floor to activate posterior chain",
    cues: "Feet hip-width | Squeeze glutes at top | 15 reps",
    explanation: "Activates the posterior chain to support the lower back and pelvis",
    warning: "Don't hyperextend the lower back",
    phases: "1,2",
    defaultRx: "2 min",
  },
  {
    id: "marching-in-place",
    name: "Marching in Place",
    category: "warmup_tool",
    targets: "Hips,Knees",
    description: "March with high knees to warm up lower body",
    cues: "Lift knees to hip height | Pump arms | 2 min",
    explanation: "Simple knee and hip flexion to increase synovial fluid flow",
    warning: "",
    phases: "1,2",
    defaultRx: "2 min",
  },
  // ── WARM-UP: Gym ──
  {
    id: "hot-tub",
    name: "Hot Tub",
    category: "warmup_tool",
    targets: "Full Body",
    description: "Warm up in hot water to increase circulation",
    cues: "2-5 min | No excessive heat",
    explanation: "Heat increases tissue elasticity and blood flow",
    warning: "Avoid if pregnant or have heart conditions",
    phases: "1,2",
    defaultRx: "5 min",
  },
  {
    id: "vibration-plate",
    name: "Vibration Plate",
    category: "warmup_tool",
    targets: "Full Body",
    description: "Stand on vibration plate for neuromuscular activation",
    cues: "Feet hip-width | Slight knee bend | 30-60 sec",
    explanation: "Vibration activates muscles and improves proprioception",
    warning: "Not for acute injuries or pregnancy",
    phases: "1,2",
    defaultRx: "1 min",
  },
  {
    id: "stationary-bike",
    name: "Stationary Bike",
    category: "warmup_tool",
    targets: "Knees,Hips",
    description: "Pedal at low resistance for continuous circular motion",
    cues: "5-10 min | Low resistance | Moderate cadence 60-80 RPM",
    explanation: "Continuous low-resistance circular motion lubricates knees and hips",
    warning: "Adjust seat height to avoid knee strain",
    phases: "1,2",
    defaultRx: "5 min",
  },
  {
    id: "elliptical",
    name: "Elliptical",
    category: "warmup_tool",
    targets: "Full Body",
    description: "Glide on elliptical for zero-impact full body warm-up",
    cues: "5-10 min | Low resistance | Natural stride",
    explanation: "Weight-bearing but zero-impact, warms entire kinetic chain",
    warning: "Start slowly; increase pace gradually",
    phases: "1,2",
    defaultRx: "5 min",
  },
  {
    id: "rowing-machine",
    name: "Rowing Machine",
    category: "warmup_tool",
    targets: "Full Body",
    description: "Row at light intensity for multi-joint warm-up",
    cues: "5 min | Low resistance | Focus on form: legs-back-arms",
    explanation: "Coordinated multi-joint extension and flexion warms shoulders, back, hips",
    warning: "Maintain neutral spine throughout",
    phases: "1,2",
    defaultRx: "5 min",
  },
  {
    id: "incline-treadmill",
    name: "Incline Treadmill Walk",
    category: "warmup_tool",
    targets: "Hips,Ankles,Calves",
    description: "Walk slowly on incline to warm up lower body",
    cues: "2.0-3.0 mph | 3-5% grade | 5-10 min",
    explanation: "Slow incline walking increases ankle dorsiflexion demands and hip extension",
    warning: "Hold rails only if needed for balance",
    phases: "1,2",
    defaultRx: "5 min",
  },
  {
    id: "stair-climber",
    name: "Stair Climber",
    category: "warmup_tool",
    targets: "Hips,Knees,Ankles",
    description: "Climb at slow tempo for functional vertical movement",
    cues: "5 min | Slow tempo | Full foot on step",
    explanation: "Functional vertical movement warms entire lower body kinetic chain",
    warning: "Maintain upright posture; don't lean on handles",
    phases: "1,2",
    defaultRx: "5 min",
  },
  // ── MOBILITY: Home ──
  {
    id: "cars-routine",
    name: "CARs Routine",
    category: "mobility",
    targets: "All Joints",
    description: "Controlled Articular Rotations for joint mobility",
    cues: "Slow circles | Full range | No momentum",
    explanation: "CARs improve joint health and body awareness",
    warning: "Move within pain-free range only",
    phases: "1,2",
    defaultRx: "5 min",
  },
  {
    id: "90-90-hip-switch",
    name: "90/90 Hip Switch",
    category: "mobility",
    targets: "Hips",
    description: "Switch legs in 90/90 position for hip mobility",
    cues: "Chest upright | Slow switch | 30 sec each side",
    explanation: "Improves hip external and internal rotation",
    warning: "Stop if sharp pain occurs",
    phases: "1,2",
    defaultRx: "30 sec each",
  },
  {
    id: "cat-cow",
    name: "Cat-Cow Stretch",
    category: "mobility",
    targets: "T-Spine,Lumbar",
    description: "Alternate between arching and rounding the spine on all fours",
    cues: "Inhale arch | Exhale round | 10-15 reps | Slow and controlled",
    explanation: "Thoracic and lumbar spinal articulation improves disc hydration",
    warning: "Move gently; avoid forcing end range",
    phases: "1,2",
    defaultRx: "2 min",
  },
  {
    id: "wall-slides",
    name: "Wall Slides",
    category: "mobility",
    targets: "Shoulders,Scapula",
    description: "Slide arms up wall to improve overhead reach",
    cues: "Back flat against wall | Arms in W position | Slide up to Y | 10 reps",
    explanation: "Builds scapular stability and improves shoulder overhead mobility",
    warning: "Keep lower back pressed against wall",
    phases: "1,2",
    defaultRx: "10 reps",
  },
  {
    id: "bird-dog",
    name: "Bird-Dog",
    category: "mobility",
    targets: "Core,Spine",
    description: "Extend opposite arm and leg from all-fours position",
    cues: "Slow extension | Hold 3 sec | Alternate sides | 8 each",
    explanation: "Core-stabilized spinal extension improves balance and coordination",
    warning: "Keep hips level; avoid rotating",
    phases: "1,2",
    defaultRx: "8 reps each",
  },
  {
    id: "doorway-chest-stretch",
    name: "Doorway Chest Stretch",
    category: "mobility",
    targets: "Chest,Shoulders",
    description: "Stretch pectorals using a doorframe for support",
    cues: "Arm at 90\u00b0 on doorframe | Lean forward gently | 30 sec each side",
    explanation: "Opens pectorals to reduce hunched posture and improve breathing",
    warning: "Don't force the stretch; ease into it",
    phases: "1,2",
    defaultRx: "30 sec each",
  },
  {
    id: "shinbox-getup",
    name: "Shinbox Get-Up",
    category: "mobility",
    targets: "Hips,Core",
    description: "Get up from shinbox position without using hands",
    cues: "Controlled movement | No hand assist | 5 reps",
    explanation: "Builds hip mobility and core stability",
    warning: "Requires significant hip mobility",
    phases: "2",
    defaultRx: "5 reps",
  },
  {
    id: "worlds-greatest-stretch",
    name: "World's Greatest Stretch",
    category: "mobility",
    targets: "Hips,T-Spine,Ankles",
    description: "Dynamic stretch targeting multiple areas",
    cues: "Lunge | Rotate | Reach | 8-10 reps each side",
    explanation: "Comprehensive dynamic mobility for warm-up",
    warning: "Avoid with acute injuries",
    phases: "1,2",
    defaultRx: "8 reps each",
  },
  {
    id: "deep-squat-hold",
    name: "Deep Squat Hold",
    category: "mobility",
    targets: "Hips,Knees,Ankles",
    description: "Hold bottom of squat position",
    cues: "Feet shoulder-width | Upright torso | Hold 30-60 sec",
    explanation: "Improves squat mechanics and ankle mobility",
    warning: "Use support if needed for balance",
    phases: "1,2",
    defaultRx: "60 sec",
  },
  {
    id: "couch-stretch",
    name: "Couch Stretch",
    category: "mobility",
    targets: "Hips,Quads",
    description: "Quad stretch on couch or box",
    cues: "Back knee elevated | Gentle forward lean | 90 sec each",
    explanation: "Improves hip and quad flexibility",
    warning: "Can be intense; progress gradually",
    phases: "1,2",
    defaultRx: "90 sec each",
  },
  {
    id: "wall-ankle-mob",
    name: "Wall Ankle Mobilization",
    category: "mobility",
    targets: "Ankles",
    description: "Mobilize ankle with wall for dorsiflexion",
    cues: "Shin against wall | Lean forward | 90 sec each",
    explanation: "Improves ankle dorsiflexion and calf mobility",
    warning: "Stop if pain in ankle",
    phases: "1,2",
    defaultRx: "90 sec each",
  },
  {
    id: "open-book",
    name: "Open Book (T-Spine)",
    category: "mobility",
    targets: "T-Spine",
    description: "Thoracic spine rotation from side-lying",
    cues: "Side-lying | Controlled rotation | 10 reps each side",
    explanation: "Improves thoracic rotation and spinal mobility",
    warning: "Avoid jerky movements",
    phases: "1,2",
    defaultRx: "10 reps each",
  },
  {
    id: "quadruped-rocking",
    name: "Quadruped Rocking",
    category: "mobility",
    targets: "Hips,Ankles",
    description: "Rock back and forth on hands and knees",
    cues: "Hands under shoulders | Slow rocks | 20 reps",
    explanation: "Improves hip and ankle mobility",
    warning: "Keep core engaged",
    phases: "1,2",
    defaultRx: "20 reps",
  },
  {
    id: "hip-flexor-pails-rails",
    name: "Hip Flexor PAILs/RAILs",
    category: "mobility",
    targets: "Hips",
    description: "Proprioceptive stretching for hip flexors",
    cues: "Hold position | Contract | Relax | 8-10 reps",
    explanation: "Increases hip flexor mobility and stability",
    warning: "Requires space and understanding of PAILs/RAILs",
    phases: "2",
    defaultRx: "8 reps",
  },
  {
    id: "90-90-pails-rails",
    name: "90/90 PAILs/RAILs",
    category: "mobility",
    targets: "Hips",
    description: "Proprioceptive stretching in 90/90 position",
    cues: "Hold | Contract | Relax | 8-10 reps each side",
    explanation: "Improves hip external rotation",
    warning: "Advanced technique; build foundation first",
    phases: "2",
    defaultRx: "8 reps each",
  },
  {
    id: "ankle-pails-rails",
    name: "Ankle PAILs/RAILs",
    category: "mobility",
    targets: "Ankles",
    description: "Proprioceptive stretching for ankle mobility",
    cues: "Hold position | Contract | Relax | 8-10 reps",
    explanation: "Improves ankle dorsiflexion and control",
    warning: "Requires proprioceptive understanding",
    phases: "2",
    defaultRx: "8 reps",
  },
  // ── MOBILITY: Gym ──
  {
    id: "dead-hang",
    name: "Dead Hang",
    category: "mobility",
    targets: "Shoulders,Spine,Grip",
    description: "Hang from bar with full body relaxed",
    cues: "Full grip | Shoulders engaged | 20-60 sec",
    explanation: "Decompresses spine and improves shoulder mobility",
    warning: "Build up duration gradually",
    phases: "1,2",
    defaultRx: "30 sec",
  },
  {
    id: "trx-squat",
    name: "TRX Assisted Squat",
    category: "mobility",
    targets: "Hips,Knees,Ankles",
    description: "Hold TRX straps for deep supported squat",
    cues: "Lean back slightly | Sink into deep squat | Hold 30 sec",
    explanation: "Deep hip and knee flexion with support allows fuller range of motion",
    warning: "Keep weight in heels; don't pull on straps",
    phases: "1,2",
    defaultRx: "30 sec",
  },
  {
    id: "cable-face-pulls",
    name: "Cable Face Pulls",
    category: "mobility",
    targets: "Shoulders,Rotator Cuff",
    description: "Pull cable rope to face level for rear deltoid and cuff work",
    cues: "Light weight | Elbows high | Squeeze shoulder blades | 12-15 reps",
    explanation: "Strengthens rear deltoids and rotator cuff for shoulder joint health",
    warning: "Use light weight; this is corrective not strength",
    phases: "1,2",
    defaultRx: "12 reps",
  },
  {
    id: "bench-tspine-stretch",
    name: "Bench T-Spine Stretch",
    category: "mobility",
    targets: "T-Spine,Lats",
    description: "Kneel and extend arms on bench for upper back opening",
    cues: "Kneel arm's length from bench | Arms on bench | Sink chest down | 30 sec",
    explanation: "Upper back extension improves thoracic mobility and lat length",
    warning: "Don't force; breathe into the stretch",
    phases: "1,2",
    defaultRx: "30 sec",
  },
  {
    id: "banded-ankle-distraction",
    name: "Banded Ankle Distraction",
    category: "mobility",
    targets: "Ankles",
    description: "Use resistance band to distract ankle joint for dorsiflexion",
    cues: "Band around ankle | Step forward into lunge | 30 sec each",
    explanation: "Band creates joint space allowing greater dorsiflexion range",
    warning: "Moderate band tension; stop if pinching",
    phases: "1,2",
    defaultRx: "30 sec each",
  },
  {
    id: "smith-machine-stretch",
    name: "Smith Machine Stretch",
    category: "mobility",
    targets: "Hamstrings,Hips",
    description: "Use smith machine bar at various heights for stretching",
    cues: "Set bar height | Leg on bar | Lean forward gently | 30 sec each",
    explanation: "Adjustable height allows progressive hamstring and hip work",
    warning: "Don't bounce; hold steady stretches",
    phases: "1,2",
    defaultRx: "30 sec each",
  },
  // ── RECOVERY: Gym ──
  {
    id: "hydro-massager",
    name: "Hydro Massager",
    category: "recovery_tool",
    targets: "Full Body",
    description: "Use hydro massager for muscle recovery",
    cues: "Various speeds | Target muscles | 5-10 min",
    explanation: "Increases circulation and aids recovery",
    warning: "Avoid over-sensitive areas",
    phases: "1,2",
    defaultRx: "5 min",
  },
  {
    id: "steam-sauna",
    name: "Steam Sauna",
    category: "recovery_tool",
    targets: "Full Body",
    description: "Relax in steam sauna for recovery",
    cues: "10-20 min | Stay hydrated | Moderate temperature",
    explanation: "Promotes relaxation and circulation",
    warning: "Avoid if pregnant or have heart conditions",
    phases: "1,2",
    defaultRx: "15 min",
  },
  {
    id: "dry-sauna",
    name: "Dry Sauna",
    category: "recovery_tool",
    targets: "Full Body",
    description: "Relax in dry sauna for muscle recovery",
    cues: "10-20 min | Stay hydrated | Moderate temperature",
    explanation: "Reduces muscle soreness and promotes recovery",
    warning: "Stay well hydrated",
    phases: "1,2",
    defaultRx: "15 min",
  },
  {
    id: "compex-warmup",
    name: "Compex \u2014 Warmup",
    category: "recovery_tool",
    targets: "Quads,Glutes",
    description: "Use Compex muscle stimulator for warm-up",
    cues: "Warmup setting | 10-15 min | Quads and glutes",
    explanation: "Prepares muscles for training",
    warning: "Follow device instructions",
    phases: "1,2",
    defaultRx: "10 min",
  },
  {
    id: "compex-recovery",
    name: "Compex \u2014 Recovery",
    category: "recovery_tool",
    targets: "Quads,Glutes,Calves",
    description: "Use Compex for post-workout recovery",
    cues: "Recovery setting | 15-20 min | Multiple muscles",
    explanation: "Aids muscle recovery and reduces soreness",
    warning: "Follow device instructions",
    phases: "1,2",
    defaultRx: "15 min",
  },
  {
    id: "compression-boots",
    name: "Compression Boots",
    category: "recovery_tool",
    targets: "Legs",
    description: "Use compression boots for leg recovery",
    cues: "15-30 min | Moderate compression | Legs only",
    explanation: "Improves circulation and reduces leg soreness",
    warning: "Start with shorter durations",
    phases: "1,2",
    defaultRx: "20 min",
  },
  // ── RECOVERY: Home ──
  {
    id: "quality-sleep",
    name: "Quality Sleep",
    category: "recovery_tool",
    targets: "Full Body",
    description: "Prioritize 7-9 hours of quality sleep for tissue repair",
    cues: "Cool room | Dark environment | Consistent schedule | No screens 1hr before",
    explanation: "The primary window for cellular tissue repair and joint recovery",
    warning: "",
    phases: "1,2",
    defaultRx: "7-9 hrs",
  },
  {
    id: "hydration",
    name: "Hydration",
    category: "recovery_tool",
    targets: "Full Body",
    description: "Drink adequate water throughout the day",
    cues: "Half body weight in oz | Sip consistently | Add electrolytes if active",
    explanation: "Maintains the volume of fluid in joint cartilage and synovial fluid",
    warning: "",
    phases: "1,2",
    defaultRx: "All day",
  },
  {
    id: "foam-roller",
    name: "Foam Roller",
    category: "recovery_tool",
    targets: "Full Body",
    description: "Roll out tight muscles for myofascial release",
    cues: "Slow rolls | 30-60 sec per area | Pause on tender spots",
    explanation: "Breaks up adhesions and improves tissue quality",
    warning: "Avoid rolling directly on joints or spine",
    phases: "1,2",
    defaultRx: "10 min",
  },
  {
    id: "tennis-ball-release",
    name: "Tennis Ball Release",
    category: "recovery_tool",
    targets: "Feet,Glutes,Upper Back",
    description: "Self-myofascial release using a tennis ball on tight spots",
    cues: "Place ball on tight area | Apply body weight | Roll slowly | 30-60 sec per spot",
    explanation: "Targeted release for tight hot spots; gentler than lacrosse ball",
    warning: "Avoid direct pressure on bones or nerves",
    phases: "1,2",
    defaultRx: "8 min",
  },
  {
    id: "lacrosse-ball",
    name: "Lacrosse Ball Release",
    category: "recovery_tool",
    targets: "Shoulders,Hips,Feet",
    description: "Targeted deep tissue release with a lacrosse ball",
    cues: "Pin and move | 30-60 sec per spot | Breathe through it",
    explanation: "Reaches deeper tissue than foam roller",
    warning: "Avoid bony areas and nerves",
    phases: "1,2",
    defaultRx: "8 min",
  },
  {
    id: "active-recovery-walk",
    name: "Active Recovery Walk",
    category: "recovery_tool",
    targets: "Full Body",
    description: "Gentle walk to flush metabolic waste and promote healing",
    cues: "15-20 min | Easy pace | Focus on breathing | Outdoors if possible",
    explanation: "Flushes metabolic waste through gentle movement without adding stress",
    warning: "",
    phases: "1,2",
    defaultRx: "15 min",
  },
  {
    id: "contrast-shower",
    name: "Contrast Shower",
    category: "recovery_tool",
    targets: "Full Body",
    description: "Alternate hot and cold water for circulation boost",
    cues: "3 min hot | 1 min cold | Repeat 3x | End on cold",
    explanation: "Promotes blood flow and reduces inflammation",
    warning: "Start gradually if new to cold exposure",
    phases: "1,2",
    defaultRx: "12 min",
  },
  {
    id: "epsom-bath",
    name: "Epsom Salt Bath",
    category: "recovery_tool",
    targets: "Full Body",
    description: "Soak in warm water with Epsom salts for recovery",
    cues: "2 cups Epsom salt | Warm water | 15-20 min soak",
    explanation: "Magnesium absorption helps muscle relaxation",
    warning: "Stay hydrated; avoid if you have low blood pressure",
    phases: "1,2",
    defaultRx: "20 min",
  },
  {
    id: "yoga-cooldown",
    name: "Yoga Cool-Down Flow",
    category: "recovery_tool",
    targets: "Full Body",
    description: "Gentle yoga sequence for recovery and relaxation",
    cues: "Child's pose | Pigeon | Supine twist | Savasana | 5 breaths each",
    explanation: "Calms nervous system and promotes recovery",
    warning: "Move gently; never force a stretch",
    phases: "1,2",
    defaultRx: "15 min",
  },
  {
    id: "self-massage",
    name: "Self-Massage (Hands/Stick)",
    category: "recovery_tool",
    targets: "Calves,Forearms,Neck",
    description: "Manual massage using hands or a massage stick",
    cues: "Slow strokes | Moderate pressure | 2-3 min per area",
    explanation: "Improves circulation and reduces muscle tension",
    warning: "Avoid inflamed or injured areas",
    phases: "1,2",
    defaultRx: "10 min",
  },
  {
    id: "massage-gun",
    name: "Massage Gun",
    category: "recovery_tool",
    targets: "Full Body",
    description: "Use percussive therapy device to break up soft tissue tension",
    cues: "30-60 sec per muscle group | Medium speed | Don't press too hard",
    explanation: "Percussive therapy increases blood flow and breaks up tension",
    warning: "Avoid bones, joints, and nerves; don't use on injuries",
    phases: "1,2",
    defaultRx: "8 min",
  },
  {
    id: "cold-plunge",
    name: "Cold Plunge",
    category: "recovery_tool",
    targets: "Full Body",
    description: "Immerse in cold water to limit acute swelling",
    cues: "2-5 min | 50-60\u00b0F water | Breathe calmly | Work up gradually",
    explanation: "Intense vasoconstriction limits acute swelling and inflammation",
    warning: "Start with 1 min; not for those with heart conditions",
    phases: "1,2",
    defaultRx: "3 min",
  },
];

export const supplements = [
  {
    id: "supp-collagen",
    name: "Collagen + Vitamin C",
    dose: "10-15g + 50mg C",
    time: "AM / Pre-workout",
    timeGroup: "am",
  },
  {
    id: "supp-omega3",
    name: "Omega-3 Fish Oil",
    dose: "~1500mg EPA+DHA",
    time: "AM with food",
    timeGroup: "am",
  },
  {
    id: "supp-vitamind",
    name: "Vitamin D3 + K2",
    dose: "2000-4000 IU + 100mcg K2",
    time: "AM with food",
    timeGroup: "am",
  },
  {
    id: "supp-creatine",
    name: "Creatine Monohydrate",
    dose: "3-5g",
    time: "AM",
    timeGroup: "am",
  },
  {
    id: "supp-curcumin",
    name: "Curcumin (w/ piperine)",
    dose: "500-1500mg",
    time: "With lunch",
    timeGroup: "mid",
  },
  {
    id: "supp-omega3b",
    name: "Omega-3 (2nd dose)",
    dose: "~1500mg EPA+DHA",
    time: "PM with dinner",
    timeGroup: "pm",
  },
  {
    id: "supp-mag",
    name: "Magnesium Glycinate",
    dose: "300-400mg",
    time: "Before bed",
    timeGroup: "pm",
  },
  {
    id: "supp-zinc",
    name: "Zinc",
    dose: "15-30mg",
    time: "With food",
    timeGroup: "am",
  },
  {
    id: "supp-ashwagandha",
    name: "Ashwagandha",
    dose: "300-600mg",
    time: "AM or PM",
    timeGroup: "am",
  },
  {
    id: "supp-glucosamine",
    name: "Glucosamine + Chondroitin",
    dose: "1500mg + 1200mg",
    time: "With food",
    timeGroup: "am",
  },
  {
    id: "supp-bcomplex",
    name: "B-Complex",
    dose: "1 capsule",
    time: "AM with food",
    timeGroup: "am",
  },
  {
    id: "supp-probiotics",
    name: "Probiotics",
    dose: "10-50 billion CFU",
    time: "AM empty stomach",
    timeGroup: "am",
  },
  {
    id: "supp-coq10",
    name: "CoQ10",
    dose: "100-200mg",
    time: "With food",
    timeGroup: "am",
  },
  {
    id: "supp-glutamine",
    name: "L-Glutamine",
    dose: "5g",
    time: "Post-workout",
    timeGroup: "mid",
  },
  {
    id: "supp-electrolytes",
    name: "Electrolytes",
    dose: "1 packet",
    time: "During workout",
    timeGroup: "mid",
  },
  {
    id: "supp-melatonin",
    name: "Melatonin",
    dose: "0.5-3mg",
    time: "30 min before bed",
    timeGroup: "pm",
  },
  {
    id: "supp-tart-cherry",
    name: "Tart Cherry Extract",
    dose: "500mg",
    time: "Before bed",
    timeGroup: "pm",
  },
  {
    id: "supp-iron",
    name: "Iron",
    dose: "18-27mg",
    time: "AM empty stomach",
    timeGroup: "am",
  },
  {
    id: "supp-vitaminc",
    name: "Vitamin C",
    dose: "500-1000mg",
    time: "AM with food",
    timeGroup: "am",
  },
];

export const milestones = [
  {
    id: "kneel",
    name: "Kneel without discomfort",
    description:
      "Kneel on a hard floor with no padding and hold comfortably for 30+ seconds. This tests knee and ankle mobility and shows your joints are adapting to load.",
  },
  {
    id: "squat60",
    name: "Deep squat hold \u2014 60 sec",
    description:
      "Hold a deep squat (full depth, heels down) for 60 seconds. A fundamental mobility benchmark that shows hip, knee, and ankle flexibility.",
  },
  {
    id: "squat120",
    name: "Deep squat hold \u2014 2 min",
    description:
      "Hold a deep squat for 2 full minutes without support. This shows strong lower-body mobility and endurance in end-range positions.",
  },
  {
    id: "hang30",
    name: "Dead hang \u2014 30 sec",
    description:
      "Hang from a pull-up bar with straight arms for 30 seconds. Builds shoulder health, grip strength, and spinal decompression.",
  },
  {
    id: "hang60",
    name: "Dead hang \u2014 60 sec",
    description:
      "Dead hang for a full minute. Demonstrates excellent shoulder mobility and grip endurance \u2014 a key joint health marker.",
  },
  {
    id: "shinbox",
    name: "Shinbox get-up without hands",
    description:
      "From a shinbox (90-90) position, stand up without using your hands. Tests hip mobility, glute strength, and balance.",
  },
  {
    id: "tgu-kb",
    name: "Turkish get-up with KB",
    description:
      "Complete a full Turkish get-up holding a kettlebell. This full-body movement tests shoulder stability, core strength, and coordinated mobility.",
  },
  {
    id: "cossack-floor",
    name: "Cossack squat \u2014 touch floor",
    description:
      "Perform a Cossack squat deep enough to touch the floor with your hand. Demands exceptional hip and ankle mobility with lateral movement.",
  },
  {
    id: "floor-nohand",
    name: "Floor to standing \u2014 no hands",
    description:
      "Get up from the floor to standing without using your hands or knees. A classic functional mobility test used in longevity research.",
  },
];

export const program = {
  name: "4-Week Joint & Mobility Program",
  durationDays: 28,
  description:
    "A hilariously serious program to get your joints moving like they should.",
};

// 28-day program template
// Weekly pattern: Day 1=gym, Day 2=home, Day 3=gym, Day 4=home, Day 5=gym, Day 6=recovery, Day 7=rest
// Repeats 4 weeks

type ProgramTemplateEntry = {
  dayNumber: number;
  dayType: string;
  exerciseId: string;
  category: string;
  sortOrder: number;
  rx: string;
};

function buildProgramTemplate(): ProgramTemplateEntry[] {
  const gymExercises: Omit<ProgramTemplateEntry, "dayNumber" | "dayType">[] = [
    { exerciseId: "hot-tub", category: "warmup_tool", sortOrder: 1, rx: "5 min" },
    { exerciseId: "vibration-plate", category: "warmup_tool", sortOrder: 2, rx: "1 min" },
    { exerciseId: "cars-routine", category: "mobility", sortOrder: 3, rx: "10 min" },
    { exerciseId: "deep-squat-hold", category: "mobility", sortOrder: 4, rx: "60 sec" },
    { exerciseId: "dead-hang", category: "mobility", sortOrder: 5, rx: "30 sec x3" },
    { exerciseId: "worlds-greatest-stretch", category: "mobility", sortOrder: 6, rx: "8 reps each" },
    { exerciseId: "hydro-massager", category: "recovery_tool", sortOrder: 9, rx: "5 min" },
    { exerciseId: "compex-recovery", category: "recovery_tool", sortOrder: 10, rx: "15 min" },
  ];

  const homeExercises: Omit<ProgramTemplateEntry, "dayNumber" | "dayType">[] = [
    { exerciseId: "cars-routine", category: "mobility", sortOrder: 1, rx: "5 min" },
    { exerciseId: "90-90-hip-switch", category: "mobility", sortOrder: 2, rx: "30 sec each" },
    { exerciseId: "couch-stretch", category: "mobility", sortOrder: 3, rx: "90 sec each" },
    { exerciseId: "wall-ankle-mob", category: "mobility", sortOrder: 4, rx: "90 sec each" },
    { exerciseId: "open-book", category: "mobility", sortOrder: 5, rx: "10 reps each" },
    { exerciseId: "quadruped-rocking", category: "mobility", sortOrder: 6, rx: "20 reps" },
  ];

  const recoveryExercises: Omit<ProgramTemplateEntry, "dayNumber" | "dayType">[] = [
    { exerciseId: "steam-sauna", category: "recovery_tool", sortOrder: 1, rx: "15 min" },
    { exerciseId: "dry-sauna", category: "recovery_tool", sortOrder: 2, rx: "15 min" },
    { exerciseId: "compression-boots", category: "recovery_tool", sortOrder: 3, rx: "20 min" },
    { exerciseId: "hydro-massager", category: "recovery_tool", sortOrder: 4, rx: "10 min" },
    { exerciseId: "compex-warmup", category: "recovery_tool", sortOrder: 5, rx: "10 min" },
  ];

  const restExercises: Omit<ProgramTemplateEntry, "dayNumber" | "dayType">[] = [
    { exerciseId: "cars-routine", category: "mobility", sortOrder: 1, rx: "5 min" },
    { exerciseId: "dead-hang", category: "mobility", sortOrder: 2, rx: "20 sec" },
    { exerciseId: "deep-squat-hold", category: "mobility", sortOrder: 3, rx: "30 sec" },
  ];

  const dayTypes = ["gym", "home", "gym", "home", "gym", "recovery", "rest"] as const;
  const exercisesByDayType: Record<string, Omit<ProgramTemplateEntry, "dayNumber" | "dayType">[]> = {
    gym: gymExercises,
    home: homeExercises,
    recovery: recoveryExercises,
    rest: restExercises,
  };

  const template: ProgramTemplateEntry[] = [];

  for (let week = 0; week < 4; week++) {
    for (let dow = 0; dow < 7; dow++) {
      const dayNumber = week * 7 + dow + 1;
      const dayType = dayTypes[dow];
      const dayExercises = exercisesByDayType[dayType];
      for (const ex of dayExercises) {
        template.push({
          dayNumber,
          dayType,
          exerciseId: ex.exerciseId,
          category: ex.category,
          sortOrder: ex.sortOrder,
          rx: ex.rx,
        });
      }
    }
  }

  return template;
}

export const programTemplate = buildProgramTemplate();
